# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import corescript_pb2 as corescript__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in corescript_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreScriptRunnerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteScript = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/ExecuteScript',
                request_serializer=corescript__pb2.ExecuteScriptRequest.SerializeToString,
                response_deserializer=corescript__pb2.ExecuteScriptResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetStatus',
                request_serializer=corescript__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.GetScriptMetadata = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetScriptMetadata',
                request_serializer=corescript__pb2.GetScriptMetadataRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetScriptMetadataResponse.FromString,
                _registered_method=True)
        self.GetScriptParameters = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetScriptParameters',
                request_serializer=corescript__pb2.GetScriptParametersRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetScriptParametersResponse.FromString,
                _registered_method=True)
        self.GetCombinedScript = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetCombinedScript',
                request_serializer=corescript__pb2.GetCombinedScriptRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetCombinedScriptResponse.FromString,
                _registered_method=True)
        self.GetBulkMetadata = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetBulkMetadata',
                request_serializer=corescript__pb2.GetBulkMetadataRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetBulkMetadataResponse.FromString,
                _registered_method=True)
        self.GetContext = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetContext',
                request_serializer=corescript__pb2.GetContextRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetContextResponse.FromString,
                _registered_method=True)
        self.CreateAndOpenWorkspace = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/CreateAndOpenWorkspace',
                request_serializer=corescript__pb2.CreateWorkspaceRequest.SerializeToString,
                response_deserializer=corescript__pb2.CreateWorkspaceResponse.FromString,
                _registered_method=True)
        self.GetScriptManifest = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetScriptManifest',
                request_serializer=corescript__pb2.GetScriptManifestRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetScriptManifestResponse.FromString,
                _registered_method=True)
        self.ValidateWorkingSet = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/ValidateWorkingSet',
                request_serializer=corescript__pb2.ValidateWorkingSetRequest.SerializeToString,
                response_deserializer=corescript__pb2.ValidateWorkingSetResponse.FromString,
                _registered_method=True)
        self.ComputeParameterOptions = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/ComputeParameterOptions',
                request_serializer=corescript__pb2.ComputeParameterOptionsRequest.SerializeToString,
                response_deserializer=corescript__pb2.ComputeParameterOptionsResponse.FromString,
                _registered_method=True)
        self.SelectElements = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/SelectElements',
                request_serializer=corescript__pb2.SelectElementsRequest.SerializeToString,
                response_deserializer=corescript__pb2.SelectElementsResponse.FromString,
                _registered_method=True)
        self.PickObject = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/PickObject',
                request_serializer=corescript__pb2.PickObjectRequest.SerializeToString,
                response_deserializer=corescript__pb2.PickObjectResponse.FromString,
                _registered_method=True)
        self.RenameScript = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/RenameScript',
                request_serializer=corescript__pb2.RenameScriptRequest.SerializeToString,
                response_deserializer=corescript__pb2.RenameScriptResponse.FromString,
                _registered_method=True)
        self.BuildScript = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/BuildScript',
                request_serializer=corescript__pb2.BuildScriptRequest.SerializeToString,
                response_deserializer=corescript__pb2.BuildScriptResponse.FromString,
                _registered_method=True)
        self.GetCategoryParameters = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetCategoryParameters',
                request_serializer=corescript__pb2.GetCategoryParametersRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetCategoryParametersResponse.FromString,
                _registered_method=True)
        self.GetModelCategories = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetModelCategories',
                request_serializer=corescript__pb2.GetModelCategoriesRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetModelCategoriesResponse.FromString,
                _registered_method=True)
        self.StopSyncSession = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/StopSyncSession',
                request_serializer=corescript__pb2.StopSyncSessionRequest.SerializeToString,
                response_deserializer=corescript__pb2.StopSyncSessionResponse.FromString,
                _registered_method=True)
        self.GetWatchdogStatus = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/GetWatchdogStatus',
                request_serializer=corescript__pb2.GetWatchdogStatusRequest.SerializeToString,
                response_deserializer=corescript__pb2.GetWatchdogStatusResponse.FromString,
                _registered_method=True)
        self.RegisterWatchdogSource = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/RegisterWatchdogSource',
                request_serializer=corescript__pb2.RegisterWatchdogSourceRequest.SerializeToString,
                response_deserializer=corescript__pb2.RegisterWatchdogSourceResponse.FromString,
                _registered_method=True)
        self.UnregisterWatchdogSource = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/UnregisterWatchdogSource',
                request_serializer=corescript__pb2.UnregisterWatchdogSourceRequest.SerializeToString,
                response_deserializer=corescript__pb2.UnregisterWatchdogSourceResponse.FromString,
                _registered_method=True)
        self.UpdateElementParameter = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/UpdateElementParameter',
                request_serializer=corescript__pb2.UpdateElementParameterRequest.SerializeToString,
                response_deserializer=corescript__pb2.UpdateElementParameterResponse.FromString,
                _registered_method=True)
        self.BatchUpdateElementParameters = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/BatchUpdateElementParameters',
                request_serializer=corescript__pb2.BatchUpdateElementParametersRequest.SerializeToString,
                response_deserializer=corescript__pb2.BatchUpdateElementParametersResponse.FromString,
                _registered_method=True)
        self.ClearAssemblyCache = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/ClearAssemblyCache',
                request_serializer=corescript__pb2.ClearAssemblyCacheRequest.SerializeToString,
                response_deserializer=corescript__pb2.ClearAssemblyCacheResponse.FromString,
                _registered_method=True)
        self.ExecuteRepl = channel.unary_unary(
                '/CoreScript.CoreScriptRunner/ExecuteRepl',
                request_serializer=corescript__pb2.ExecuteReplRequest.SerializeToString,
                response_deserializer=corescript__pb2.ExecuteReplResponse.FromString,
                _registered_method=True)


class CoreScriptRunnerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScriptMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScriptParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCombinedScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBulkMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAndOpenWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScriptManifest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateWorkingSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeParameterOptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectElements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PickObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategoryParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSyncSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWatchdogStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWatchdogSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterWatchdogSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateElementParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUpdateElementParameters(self, request, context):
        """New V4 Data Grid Feature: Mass Single-Transaction Edit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearAssemblyCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteRepl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreScriptRunnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteScript': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteScript,
                    request_deserializer=corescript__pb2.ExecuteScriptRequest.FromString,
                    response_serializer=corescript__pb2.ExecuteScriptResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=corescript__pb2.GetStatusRequest.FromString,
                    response_serializer=corescript__pb2.GetStatusResponse.SerializeToString,
            ),
            'GetScriptMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScriptMetadata,
                    request_deserializer=corescript__pb2.GetScriptMetadataRequest.FromString,
                    response_serializer=corescript__pb2.GetScriptMetadataResponse.SerializeToString,
            ),
            'GetScriptParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScriptParameters,
                    request_deserializer=corescript__pb2.GetScriptParametersRequest.FromString,
                    response_serializer=corescript__pb2.GetScriptParametersResponse.SerializeToString,
            ),
            'GetCombinedScript': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCombinedScript,
                    request_deserializer=corescript__pb2.GetCombinedScriptRequest.FromString,
                    response_serializer=corescript__pb2.GetCombinedScriptResponse.SerializeToString,
            ),
            'GetBulkMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBulkMetadata,
                    request_deserializer=corescript__pb2.GetBulkMetadataRequest.FromString,
                    response_serializer=corescript__pb2.GetBulkMetadataResponse.SerializeToString,
            ),
            'GetContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContext,
                    request_deserializer=corescript__pb2.GetContextRequest.FromString,
                    response_serializer=corescript__pb2.GetContextResponse.SerializeToString,
            ),
            'CreateAndOpenWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAndOpenWorkspace,
                    request_deserializer=corescript__pb2.CreateWorkspaceRequest.FromString,
                    response_serializer=corescript__pb2.CreateWorkspaceResponse.SerializeToString,
            ),
            'GetScriptManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScriptManifest,
                    request_deserializer=corescript__pb2.GetScriptManifestRequest.FromString,
                    response_serializer=corescript__pb2.GetScriptManifestResponse.SerializeToString,
            ),
            'ValidateWorkingSet': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateWorkingSet,
                    request_deserializer=corescript__pb2.ValidateWorkingSetRequest.FromString,
                    response_serializer=corescript__pb2.ValidateWorkingSetResponse.SerializeToString,
            ),
            'ComputeParameterOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeParameterOptions,
                    request_deserializer=corescript__pb2.ComputeParameterOptionsRequest.FromString,
                    response_serializer=corescript__pb2.ComputeParameterOptionsResponse.SerializeToString,
            ),
            'SelectElements': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectElements,
                    request_deserializer=corescript__pb2.SelectElementsRequest.FromString,
                    response_serializer=corescript__pb2.SelectElementsResponse.SerializeToString,
            ),
            'PickObject': grpc.unary_unary_rpc_method_handler(
                    servicer.PickObject,
                    request_deserializer=corescript__pb2.PickObjectRequest.FromString,
                    response_serializer=corescript__pb2.PickObjectResponse.SerializeToString,
            ),
            'RenameScript': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameScript,
                    request_deserializer=corescript__pb2.RenameScriptRequest.FromString,
                    response_serializer=corescript__pb2.RenameScriptResponse.SerializeToString,
            ),
            'BuildScript': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildScript,
                    request_deserializer=corescript__pb2.BuildScriptRequest.FromString,
                    response_serializer=corescript__pb2.BuildScriptResponse.SerializeToString,
            ),
            'GetCategoryParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategoryParameters,
                    request_deserializer=corescript__pb2.GetCategoryParametersRequest.FromString,
                    response_serializer=corescript__pb2.GetCategoryParametersResponse.SerializeToString,
            ),
            'GetModelCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelCategories,
                    request_deserializer=corescript__pb2.GetModelCategoriesRequest.FromString,
                    response_serializer=corescript__pb2.GetModelCategoriesResponse.SerializeToString,
            ),
            'StopSyncSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSyncSession,
                    request_deserializer=corescript__pb2.StopSyncSessionRequest.FromString,
                    response_serializer=corescript__pb2.StopSyncSessionResponse.SerializeToString,
            ),
            'GetWatchdogStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWatchdogStatus,
                    request_deserializer=corescript__pb2.GetWatchdogStatusRequest.FromString,
                    response_serializer=corescript__pb2.GetWatchdogStatusResponse.SerializeToString,
            ),
            'RegisterWatchdogSource': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWatchdogSource,
                    request_deserializer=corescript__pb2.RegisterWatchdogSourceRequest.FromString,
                    response_serializer=corescript__pb2.RegisterWatchdogSourceResponse.SerializeToString,
            ),
            'UnregisterWatchdogSource': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterWatchdogSource,
                    request_deserializer=corescript__pb2.UnregisterWatchdogSourceRequest.FromString,
                    response_serializer=corescript__pb2.UnregisterWatchdogSourceResponse.SerializeToString,
            ),
            'UpdateElementParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateElementParameter,
                    request_deserializer=corescript__pb2.UpdateElementParameterRequest.FromString,
                    response_serializer=corescript__pb2.UpdateElementParameterResponse.SerializeToString,
            ),
            'BatchUpdateElementParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchUpdateElementParameters,
                    request_deserializer=corescript__pb2.BatchUpdateElementParametersRequest.FromString,
                    response_serializer=corescript__pb2.BatchUpdateElementParametersResponse.SerializeToString,
            ),
            'ClearAssemblyCache': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearAssemblyCache,
                    request_deserializer=corescript__pb2.ClearAssemblyCacheRequest.FromString,
                    response_serializer=corescript__pb2.ClearAssemblyCacheResponse.SerializeToString,
            ),
            'ExecuteRepl': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteRepl,
                    request_deserializer=corescript__pb2.ExecuteReplRequest.FromString,
                    response_serializer=corescript__pb2.ExecuteReplResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CoreScript.CoreScriptRunner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CoreScript.CoreScriptRunner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreScriptRunner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/ExecuteScript',
            corescript__pb2.ExecuteScriptRequest.SerializeToString,
            corescript__pb2.ExecuteScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetStatus',
            corescript__pb2.GetStatusRequest.SerializeToString,
            corescript__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScriptMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetScriptMetadata',
            corescript__pb2.GetScriptMetadataRequest.SerializeToString,
            corescript__pb2.GetScriptMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScriptParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetScriptParameters',
            corescript__pb2.GetScriptParametersRequest.SerializeToString,
            corescript__pb2.GetScriptParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCombinedScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetCombinedScript',
            corescript__pb2.GetCombinedScriptRequest.SerializeToString,
            corescript__pb2.GetCombinedScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBulkMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetBulkMetadata',
            corescript__pb2.GetBulkMetadataRequest.SerializeToString,
            corescript__pb2.GetBulkMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetContext',
            corescript__pb2.GetContextRequest.SerializeToString,
            corescript__pb2.GetContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAndOpenWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/CreateAndOpenWorkspace',
            corescript__pb2.CreateWorkspaceRequest.SerializeToString,
            corescript__pb2.CreateWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScriptManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetScriptManifest',
            corescript__pb2.GetScriptManifestRequest.SerializeToString,
            corescript__pb2.GetScriptManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateWorkingSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/ValidateWorkingSet',
            corescript__pb2.ValidateWorkingSetRequest.SerializeToString,
            corescript__pb2.ValidateWorkingSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeParameterOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/ComputeParameterOptions',
            corescript__pb2.ComputeParameterOptionsRequest.SerializeToString,
            corescript__pb2.ComputeParameterOptionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectElements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/SelectElements',
            corescript__pb2.SelectElementsRequest.SerializeToString,
            corescript__pb2.SelectElementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PickObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/PickObject',
            corescript__pb2.PickObjectRequest.SerializeToString,
            corescript__pb2.PickObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/RenameScript',
            corescript__pb2.RenameScriptRequest.SerializeToString,
            corescript__pb2.RenameScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/BuildScript',
            corescript__pb2.BuildScriptRequest.SerializeToString,
            corescript__pb2.BuildScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCategoryParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetCategoryParameters',
            corescript__pb2.GetCategoryParametersRequest.SerializeToString,
            corescript__pb2.GetCategoryParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetModelCategories',
            corescript__pb2.GetModelCategoriesRequest.SerializeToString,
            corescript__pb2.GetModelCategoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSyncSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/StopSyncSession',
            corescript__pb2.StopSyncSessionRequest.SerializeToString,
            corescript__pb2.StopSyncSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWatchdogStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/GetWatchdogStatus',
            corescript__pb2.GetWatchdogStatusRequest.SerializeToString,
            corescript__pb2.GetWatchdogStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWatchdogSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/RegisterWatchdogSource',
            corescript__pb2.RegisterWatchdogSourceRequest.SerializeToString,
            corescript__pb2.RegisterWatchdogSourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterWatchdogSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/UnregisterWatchdogSource',
            corescript__pb2.UnregisterWatchdogSourceRequest.SerializeToString,
            corescript__pb2.UnregisterWatchdogSourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateElementParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/UpdateElementParameter',
            corescript__pb2.UpdateElementParameterRequest.SerializeToString,
            corescript__pb2.UpdateElementParameterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchUpdateElementParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/BatchUpdateElementParameters',
            corescript__pb2.BatchUpdateElementParametersRequest.SerializeToString,
            corescript__pb2.BatchUpdateElementParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearAssemblyCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/ClearAssemblyCache',
            corescript__pb2.ClearAssemblyCacheRequest.SerializeToString,
            corescript__pb2.ClearAssemblyCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteRepl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.CoreScriptRunner/ExecuteRepl',
            corescript__pb2.ExecuteReplRequest.SerializeToString,
            corescript__pb2.ExecuteReplResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AddinBridgeStub(object):
    """Internal service for the Revit Add-in to talk to the Sidecar
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/CoreScript.AddinBridge/Subscribe',
                request_serializer=corescript__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=corescript__pb2.TaskEnvelope.FromString,
                _registered_method=True)
        self.SubmitResult = channel.unary_unary(
                '/CoreScript.AddinBridge/SubmitResult',
                request_serializer=corescript__pb2.TaskResult.SerializeToString,
                response_deserializer=corescript__pb2.SubmitResultResponse.FromString,
                _registered_method=True)


class AddinBridgeServicer(object):
    """Internal service for the Revit Add-in to talk to the Sidecar
    """

    def Subscribe(self, request, context):
        """Add-in calls this to receive tasks from the Sidecar
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResult(self, request, context):
        """Add-in calls this to submit the result of a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddinBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=corescript__pb2.SubscribeRequest.FromString,
                    response_serializer=corescript__pb2.TaskEnvelope.SerializeToString,
            ),
            'SubmitResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitResult,
                    request_deserializer=corescript__pb2.TaskResult.FromString,
                    response_serializer=corescript__pb2.SubmitResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CoreScript.AddinBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CoreScript.AddinBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AddinBridge(object):
    """Internal service for the Revit Add-in to talk to the Sidecar
    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/CoreScript.AddinBridge/Subscribe',
            corescript__pb2.SubscribeRequest.SerializeToString,
            corescript__pb2.TaskEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoreScript.AddinBridge/SubmitResult',
            corescript__pb2.TaskResult.SerializeToString,
            corescript__pb2.SubmitResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
